name: intera
description: Intera - Divida suas contas com seus amigos!

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  get: ^4.5.1
  responsive_framework: ^0.1.5
  brasil_fields: ^1.3.0
  animate_do: ^2.0.0
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  firebase_crashlytics: ^2.3.0
  google_sign_in: ^5.2.1
  flutter_secure_storage: ^5.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 
  mockito: ^5.0.16
  faker: ^2.0.0
  build_runner: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/thin.ttf
          weight: 100
        - asset: assets/fonts/inter/light.ttf
          weight: 300
        - asset: assets/fonts/inter/regular.ttf
          weight: 400
        - asset: assets/fonts/inter/medium.ttf
          weight: 500
        - asset: assets/fonts/inter/semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter/bold.ttf
          weight: 700