// Mocks generated by Mockito 5.0.16 from annotations
// in intera/test/layers/domain/usecases/authenticate_with_email_and_password_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:intera/layers/data/datasources/authentication/authentication_datasource.dart'
    as _i3;
import 'package:intera/layers/data/dto/user_dto.dart' as _i2;
import 'package:intera/layers/domain/entities/CredentialsEntity.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserDto_0 extends _i1.Fake implements _i2.UserDto {}

/// A class which mocks [AuthenticationDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationDatasource extends _i1.Mock
    implements _i3.AuthenticationDatasource {
  MockAuthenticationDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserDto> authenticateWithEmailAndPassword(
          _i5.CredentialsEntity? credentials) =>
      (super.noSuchMethod(
          Invocation.method(#authenticateWithEmailAndPassword, [credentials]),
          returnValue:
              Future<_i2.UserDto>.value(_FakeUserDto_0())) as _i4
          .Future<_i2.UserDto>);
  @override
  _i4.Future<_i2.UserDto> authenticateWithGoogle() =>
      (super.noSuchMethod(Invocation.method(#authenticateWithGoogle, []),
              returnValue: Future<_i2.UserDto>.value(_FakeUserDto_0()))
          as _i4.Future<_i2.UserDto>);
  @override
  String toString() => super.toString();
}
